server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

  instance:
    prefer-ip-address: true
    
spring:
  cloud:
    gateway:
      routes:
        - id: reports-service
          uri: lb://REPORTS-SERVICE
          predicates:
            - Path=/api/reports/**
          filters:
            - StripPrefix=1

        - id: bootcoin-service
          uri: lb://BOOTCOIN-SERVICE
          predicates:
            - Path=/api/bootcoin/**
          filters:
            - StripPrefix=2
