server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

  instance:
    prefer-ip-address: true
    
spring:
  cloud:
    gateway:
      routes:
        - id: bootcoin-service
          uri: lb://BOOTCOIN-SERVICE
          predicates:
            - Path=/api/bootcoin/**
          filters:
            - StripPrefix=2

        - id: cards-service
          uri: lb://CARDS-SERVICE
          predicates:
            - Path=/api/cards/**
          filters:
            - StripPrefix=1

        - id: customers-service
          uri: lb://CUSTOMERS-SERVICE
          predicates:
            - Path=/api/customers/**
          filters:
            - StripPrefix=1

        - id: customers-service
          uri: lb://CUSTOMERS-SERVICE
          predicates:
            - Path=/api/customers/**
          filters:
            - StripPrefix=1
            
        - id: reports-service
          uri: lb://REPORTS-SERVICE
          predicates:
            - Path=/api/reports/**
          filters:
            - StripPrefix=1

        - id: users-service
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1

        - id: wallets-service
          uri: lb://WALLETS
          predicates:
            - Path=/api/wallets/**
          filters:
            - StripPrefix=1
