server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
      
  instance:
    prefer-ip-address: true

spring:
  data:
    mongodb:
      # uri: mongodb://localhost:27017/bootcoindb
      uri: mongodb://mongo-bankx:27017/bootcoindb