server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
      
  instance:
    prefer-ip-address: true

external:
  accounts:
    service-id: core-banking-service
    endpoints:
      withdraw: /core-banking/accounts/{accountId}/withdraw
      balance: /cards/customer/{accountId}/balance

spring:
  data:
    mongodb:
      # uri: mongodb://localhost:27017/cardsdb
      uri: mongodb://mongo-bankx:27017/cardsdb
