server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
      
  instance:
    prefer-ip-address: true

spring:
  data:
    mongodb:
      # uri: mongodb://localhost:27017/reports-db
      uri: mongodb://mongo-bankx:27017/reports-db

  kafka:
    bootstrap-servers: broker:29092

    consumer:
      group-id: account-service
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
